// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
export interface Env {
    CHAT_R2: R2Bucket;
    USER_KV: KVNamespace;
    ASSETS: { fetch: (request: Request) => Promise<Response> };
    OPENROUTER_BASE_URL: string;
    OPENROUTER_FREE_KEY: string;
    MCP_SERVER_URL: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GOOGLE_CLENDAR_REDIRECT_URI: string;
    GOOGLE_GMAIL_REDIRECT_URI: string;
}
